pluginManagement {
    repositories {
        exclusiveContent {
            forRepository { maven { name = 'Fabric'; url = uri('https://maven.fabricmc.net') } }
            filter { includeGroupAndSubgroups('net.fabricmc') }
        }
        gradlePluginPortal()
        mavenCentral()
    }
}
rootProject.name = 'mtmc-peer-lab'
